import { AppConfig } from "./types";

export const DEFAULT_CONFIG: AppConfig = {
  partnerName: "Yudia",
  questions: [
    {
      id: 1,
      text: "Di mana tempat pertama kali kita kencan?",
      answer: "Bandung",
      hint: "Ibu kota Jawa Barat yang sejuk, dingin, dan penuh kenangan romantis kita.",
    },
    {
      id: 2,
      text: "Apa makanan favoritku yang sering kita makan bareng?",
      answer: "Nasi Goreng",
      hint: "Nasi gurih wangi yang digoreng hangat, biasanya pakai telur ceplok kesukaan kita!",
    },
    {
      id: 3,
      text: "Tanggal berapa hari ulang tahun Yudia? (Format: DD/MM)",
      answer: "14/09",
      hint: "Hari paling spesial ketika bidadari lahir ke dunia! Contoh formatnya: 14/09",
    },
  ],
  memories: [
    {
      id: 1,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/1.jpg",
      title: "Momen Indah Kita #1",
      date: "September 2026",
      caption: "Di setiap langkah, bayangmu selalu hadir membawa rona bahagia...",
    },
    {
      id: 2,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/2.jpg",
      title: "Momen Indah Kita #2",
      date: "September 2026",
      caption: "Senyummu bagaikan mentari fajar yang menghapus embun dingin...",
    },
    {
      id: 3,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/3.jpg",
      title: "Momen Indah Kita #3",
      date: "September 2026",
      caption: "Tawa manismu adalah melodi terindah yang selalu ingin kudengar...",
    },
    {
      id: 4,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/4.jpg",
      title: "Momen Indah Kita #4",
      date: "September 2026",
      caption: "Dalam matamu, kutemukan tempat ternyaman untuk pulang...",
    },
    {
      id: 5,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/5.jpg",
      title: "Momen Indah Kita #5",
      date: "September 2026",
      caption: "Seperti rintik hujan hangat yang menyejukkan jiwa...",
    },
    {
      id: 6,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/6.jpg",
      title: "Momen Indah Kita #6",
      date: "September 2026",
      caption: "Kamu adalah untaian doa terbaik yang dikabulkan semesta...",
    },
    {
      id: 7,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/7.jpg",
      title: "Momen Indah Kita #7",
      date: "September 2026",
      caption: "Setiap hari bersamamu adalah cerita favorit yang kutulis di hati...",
    },
    {
      id: 8,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/8.jpg",
      title: "Momen Indah Kita #8",
      date: "September 2026",
      caption: "Kehangatan tanganmu menghapus segala gundah gulana...",
    },
    {
      id: 9,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/9.jpg",
      title: "Momen Indah Kita #9",
      date: "September 2026",
      caption: "Satu detak jantung kita mengalunkan irama rindu yang tiada habis...",
    },
    {
      id: 10,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/10.jpg",
      title: "Momen Indah Kita #10",
      date: "September 2026",
      caption: "Denganmu, duniaku selalu dipenuhi warna-warni pelangi...",
    },
    {
      id: 11,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/11.jpg",
      title: "Momen Indah Kita #11",
      date: "September 2026",
      caption: "Senyuman itu yang selalu membuat duniaku berputar lebih indah...",
    },
    {
      id: 12,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/12.jpg",
      title: "Momen Indah Kita #12",
      date: "September 2026",
      caption: "Menyusuri jalan bersamamu membuat perjalanan terjauh terasa singkat...",
    },
    {
      id: 13,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/13.jpg",
      title: "Momen Indah Kita #13",
      date: "September 2026",
      caption: "Terima kasih untuk setiap canda tawa yang menghidupkan jiwaku...",
    },
    {
      id: 14,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/14.jpg",
      title: "Momen Indah Kita #14",
      date: "September 2026",
      caption: "Dua hati yang saling bertaut dalam kelembutan takdir...",
    },
    {
      id: 15,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/15.jpg",
      title: "Momen Indah Kita #15",
      date: "September 2026",
      caption: "Kamu adalah keindahan paling nyata yang pernah kutemui...",
    },
    {
      id: 16,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/16.jpg",
      title: "Momen Indah Kita #16",
      date: "September 2026",
      caption: "Di sini, dalam dekapmu, waktu serasa berhenti berputar...",
    },
    {
      id: 17,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/17.jpg",
      title: "Momen Indah Kita #17",
      date: "September 2026",
      caption: "Setiap senja terasa lebih syahdu saat kutatap bersamamu...",
    },
    {
      id: 18,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/18.jpg",
      title: "Momen Indah Kita #18",
      date: "September 2026",
      caption: "Kecantikan hatimu memancar tulus dalam tatap mata indahmu...",
    },
    {
      id: 19,
      imageUrl: "https://raw.githubusercontent.com/aditysm/ngetes/main/19.jpg",
      title: "Masa-Masa Indah #19",
      date: "September 2026",
      caption: "19 tahun usiamu membawa kebahagiaan tak terukur bagi orang-orang sekitar...",
    },
  ],
  gdriveUrl: "https://drive.google.com/drive/folders/1abc123_your_romantic_memories_placeholder",
  musicUrl: "https://www.dropbox.com/scl/fi/5ytyvkky1o0n3z0webi12/Jika-Kamu-Benar-benar-Mengenalku.mp3?rlkey=xupt26zbniyyvi8v02m0vqv3k&st=kzxb2308&dl=1",
  loveLetter: "Hai sayangku, Yudia tercinta.\n\nSelamat ulang tahun ya manis! Hari ini adalah hari favoritku karena di hari inilah kamu dilahirkan ke dunia. Aku sangat bersyukur bisa memilikimu di sisiku.\n\nTerima kasih ya sudah selalu sabar, pengertian, dan selalu menghujani aku dengan senyum manis kamu yang ga pernah gagal bikin hari-hariku jadi jauh lebih cerah.\n\nSemoga di usia yang baru ini kamu selalu sehat, bahagia, dan semua impian indahmu satu per satu terwujud. Ingat ya, aku bakal selalu ada di sini untuk mendukungmu dan berjalan bersamamu melewati setiap musim kehidupan.\n\nAku sayang kamu, sekarang, besok, dan selamanya.",
};
